### ISSUE TITLE
HUB: Proof of concept 08/06

### ISSUE THREAD

**Issue by kbrimm** [Plantalytics/plantalytics-hub#6]
- [x] MQTT acts as message broker, accepts incoming messages
- [x] Script parses message feed
- [ ] Script pushes payload to back end.
